language: python
env:
  - REPO=lyft/omnibot
sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile -t $REPO:$TRAVIS_COMMIT .
  - docker run -v $PWD/omnibot/dist:/tmp/dist $REPO:$TRAVIS_COMMIT /bin/sh -c "cp -r /srv/omnibot/omnibot/dist/. /tmp/dist/."
install:
  - gem install travis --no-rdoc --no-ri
script:
  - travis lint .travis.yml --skip-completion-check
  - docker run $REPO:$TRAVIS_COMMIT /bin/sh -c "make test"
after_success:
  - ./docker_push.sh
